name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            artifact_name: nib-linux-amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        go mod download
        go build -ldflags "-s -w" -o ${{ matrix.artifact_name }} main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create release archive
      run: |
        # Create release directory
        mkdir -p release
        
        # List current directory contents for debugging
        echo "Current directory contents:"
        ls -la
        
        # Extract artifacts from directories and move to release directory
        for dir in nib-*; do
          if [[ -d "$dir" ]]; then
            echo "Processing directory: $dir"
            # Find the actual executable file in the directory
            for file in "$dir"/*; do
              if [[ -f "$file" ]]; then
                filename=$(basename "$file")
                echo "Moving $file to release/$filename"
                cp "$file" "release/$filename"
              fi
            done
          fi
        done
        
        # Create compressed archives
        cd release
        echo "Release directory contents:"
        ls -la
        
        # Create compressed archive for Linux amd64
        if [[ -f "nib-linux-amd64" ]]; then
          echo "Creating archive for: nib-linux-amd64"
          tar -czf nib-linux-amd64.tar.gz nib-linux-amd64
        fi
        
        # Create checksums for files only (not directories)
        sha256sum nib-* > checksums.txt
        
        echo "Final release contents:"
        ls -la

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 